name: CodeWithSaar.Extensions.Logging.File Beta Package

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack CodeWithSaar.Extensions.Logging.File/CodeWithSaar.Extensions.Logging.File.csproj --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push CodeWithSaar.Extensions.Logging.File.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_PAT}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_PAT }}