name: Build example

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore ./examples/WebAPIExample/WebAPIExample.csproj
    - name: Build
      run: dotnet build --no-restore ./examples/WebAPIExample/WebAPIExample.csproj
